steps:
- id: "build"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/futurae-app/futurae$TAG_NAME', '.']
  waitFor: ['-']

- id: "retag"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push',  'europe-west1-docker.pkg.dev/${PROJECT_ID}/futurae-app/futurae$TAG_NAME']

images:
  - 'europe-west1-docker.pkg.dev/${PROJECT_ID}/futurae-app/futurae$TAG_NAME'

