steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/${PROJECT_ID}/futurae-app/futurae:$COMMIT_SHA', '.']

# Scan the Docker image using Grype
- name: 'anchore/grype:latest'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      grype -v jsoneurope-west1-docker.pkg.dev/${PROJECT_ID}/futurae-app/futurae:$COMMIT_SHA
 
