version: '3'

services:
 futurae-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: futurae
    ports:
      - 5000:5000
    environment:
      - PROJECT_ID=prj-futurae-d51c
      - BUCKET_NAME=prj-futurae-d51c-futurae-bucket
      - CLOUDSDK_CONFIG=/gcp/config
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/application_default_credentials.json
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/gcp/config/application_default_credentials.json:ro